name: 04 - Using Actions
on: 
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: CD into react app folder
              working-directory: './04-using-actions'
              run: ls -la
            - name: Setup Node
              uses: actions/setup-node@v4
              with: 
                node-version: 'latest'
            - name: Install Dependencies
              run: npm ci
