name: 04 - Using Actions
on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './04-using-actions/my-app'
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: CD into react app folder
              run: ls -la
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: Install Dependencies
              run: npm ci
            - name: Run Unit Tests
              run: npm run lint
