name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: Test value
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps: 
            - if: ${{inputs.debug}} == true 
              run: |
                echo "[debug] Print start-up data"
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Branch: ${{ github.ref_name }}"