name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                description: Test value
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug: ${{ inputs.debug }}] Print start-up data'
              if: ${{inputs.debug}} == true
              run: |
                  echo "Triggered by: ${{ github.event_name }}"
                  echo "Branch: ${{ github.ref }}"
                  echo "Branch: ${{ github.ref_name }}"
            - name: '[debug: ${{ inputs.debug }}] Print when triggered from main'
              if: ${{ github.ref_name }} == "main" && ${{inputs.debug}} == true
              run: echo "I was triggered from main"
